openapi: 3.0.2
info:
  description: REST API for management of Baseten resources
  title: Baseten management API
  version: 1.0.0
  x-konfig-has-globally-required-security: true
servers:
- url: https://api.baseten.co
security:
- ApiKeyAuth: []
tags:
- name: Model
- name: Deployment
- name: AutoscalingSetting
- name: Secret
paths:
  /v1/secrets:
    get:
      operationId: Secret_getAllSecrets
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretsV1'
          description: A list of Baseten secrets.
      summary: Gets all secrets
      tags:
      - Secret
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-secrets
      x-accepts: application/json
    post:
      description: Creates a new secret or updates an existing secret if one with
        the provided name already exists. The name and creation date of the created
        or updated secret is returned.
      operationId: Secret_upsertNewSecret
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertSecretRequestV1'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretV1'
          description: A Baseten secret. Note that we do not support retrieving secret
            values.
      summary: Upserts a secret
      tags:
      - Secret
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-secrets
      x-content-type: application/json
      x-accepts: application/json
  /v1/models:
    get:
      operationId: Model_getAllModels
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelsV1'
          description: A list of models.
      summary: Gets all models
      tags:
      - Model
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-models
      x-accepts: application/json
  /v1/models/{model_id}:
    get:
      operationId: Model_getModelById
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelV1'
          description: A model.
      summary: Gets a model by ID
      tags:
      - Model
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-models-model_id
      x-accepts: application/json
  /v1/models/{model_id}/deployments:
    get:
      operationId: Model_getAllDeployments
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentsV1'
          description: A list of deployments of a model.
      summary: Gets all deployments of a model
      tags:
      - Model
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments
      x-accepts: application/json
  /v1/models/{model_id}/deployments/development:
    get:
      description: Gets a model's development deployment and returns the deployment.
      operationId: Deployment_getDevelopmentDetails
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentV1'
          description: A deployment of a model.
      summary: Gets a model's development deployment
      tags:
      - Deployment
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments-development
      x-accepts: application/json
  /v1/models/{model_id}/deployments/production:
    get:
      description: Gets a model's production deployment and returns the deployment.
      operationId: Deployment_getProductionDetails
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentV1'
          description: A deployment of a model.
      summary: Gets a model's production deployment
      tags:
      - Deployment
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments-production
      x-accepts: application/json
  /v1/models/{model_id}/deployments/{deployment_id}:
    get:
      description: Gets a model's deployment by id and returns the deployment.
      operationId: Deployment_detailsGet
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: deployment_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentV1'
          description: A deployment of a model.
      summary: Gets a model's deployment by id
      tags:
      - Deployment
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments-deployment_id
      x-accepts: application/json
  /v1/models/{model_id}/deployments/development/autoscaling_settings:
    patch:
      description: Updates a development deployment's autoscaling settings and returns
        the update status.
      operationId: AutoscalingSetting_updateDevelopmentSetting
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAutoscalingSettingsV1'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAutoscalingSettingsResponseV1'
          description: The response to a request to update autoscaling settings.
      summary: Updates a development deployment's autoscaling settings
      tags:
      - AutoscalingSetting
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--v1-models-model_id-deployments-development-autoscaling_settings
      x-content-type: application/json
      x-accepts: application/json
  /v1/models/{model_id}/deployments/production/autoscaling_settings:
    patch:
      description: Updates a production deployment's autoscaling settings and returns
        the update status.
      operationId: AutoscalingSetting_updateStatus
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAutoscalingSettingsV1'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAutoscalingSettingsResponseV1'
          description: The response to a request to update autoscaling settings.
      summary: Updates a production deployment's autoscaling settings
      tags:
      - AutoscalingSetting
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--v1-models-model_id-deployments-production-autoscaling_settings
      x-content-type: application/json
      x-accepts: application/json
  /v1/models/{model_id}/deployments/{deployment_id}/autoscaling_settings:
    patch:
      description: Updates a deployment's autoscaling settings and returns the update
        status.
      operationId: AutoscalingSetting_updateDeploymentSettings
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: deployment_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAutoscalingSettingsV1'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAutoscalingSettingsResponseV1'
          description: The response to a request to update autoscaling settings.
      summary: Updates a deployment's autoscaling settings
      tags:
      - AutoscalingSetting
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--v1-models-model_id-deployments-deployment_id-autoscaling_settings
      x-content-type: application/json
      x-accepts: application/json
  /v1/models/{model_id}/deployments/development/promote:
    post:
      description: "Creates a new production deployment from the development deployment,\
        \ the currently building deployment is returned."
      operationId: Model_deployPromote
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoteRequestV1'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentV1'
          description: A deployment of a model.
      summary: Promotes a development deployment to production
      tags:
      - Model
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-models-model_id-deployments-development-promote
      x-content-type: application/json
      x-accepts: application/json
  /v1/models/{model_id}/deployments/{deployment_id}/promote:
    post:
      description: Promotes an existing deployment to production and returns the same
        deployment.
      operationId: Model_deploymentPromote
      parameters:
      - explode: false
        in: path
        name: model_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: deployment_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoteRequestV1'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentV1'
          description: A deployment of a model.
      summary: Promotes a deployment to production
      tags:
      - Model
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-models-model_id-deployments-deployment_id-promote
      x-content-type: application/json
      x-accepts: application/json
components:
  parameters:
    model_id:
      explode: false
      in: path
      name: model_id
      required: true
      schema:
        type: string
      style: simple
    deployment_id:
      explode: false
      in: path
      name: deployment_id
      required: true
      schema:
        type: string
      style: simple
  schemas:
    SecretV1:
      description: A Baseten secret. Note that we do not support retrieving secret
        values.
      example:
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
      properties:
        created_at:
          description: Time the secret was created in ISO 8601 format
          format: date-time
          title: Created At
          type: string
        name:
          description: Name of the secret
          title: Name
          type: string
      required:
      - created_at
      - name
      title: SecretV1
      type: object
      x-konfig-is-used-in-successful-response: true
    SecretsV1:
      description: A list of Baseten secrets.
      example:
        secrets:
        - name: name
          created_at: 2000-01-23T04:56:07.000+00:00
        - name: name
          created_at: 2000-01-23T04:56:07.000+00:00
      properties:
        secrets:
          items:
            $ref: '#/components/schemas/SecretV1'
          title: Secrets
          type: array
      required:
      - secrets
      title: SecretsV1
      type: object
      x-konfig-is-used-in-successful-response: true
    UpsertSecretRequestV1:
      description: A request to create or update a Baseten secret by name.
      example:
        name: name
        value: value
      properties:
        name:
          description: Name of the new or existing secret
          title: Name
          type: string
        value:
          description: Value of the secret
          title: Value
          type: string
      required:
      - name
      - value
      title: UpsertSecretRequestV1
      type: object
    ModelV1:
      description: A model.
      example:
        development_deployment_id: development_deployment_id
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        deployments_count: 0
        instance_type_name: instance_type_name
        id: id
        production_deployment_id: production_deployment_id
      properties:
        id:
          description: Unique identifier of the model
          title: Id
          type: string
        created_at:
          description: Time the model was created in ISO 8601 format
          format: date-time
          title: Created At
          type: string
        name:
          description: Name of the model
          title: Name
          type: string
        deployments_count:
          description: Number of deployments of the model
          title: Deployments Count
          type: integer
        production_deployment_id:
          description: Unique identifier of the production deployment of the model
          title: Production Deployment Id
          type: string
        development_deployment_id:
          description: Unique identifier of the development deployment of the model
          title: Development Deployment Id
          type: string
        instance_type_name:
          description: Name of the instance type the model is deployed on
          title: Instance Type Name
          type: string
      required:
      - created_at
      - deployments_count
      - development_deployment_id
      - id
      - instance_type_name
      - name
      - production_deployment_id
      title: ModelV1
      type: object
      x-konfig-is-used-in-successful-response: true
    ModelsV1:
      description: A list of models.
      example:
        models:
        - development_deployment_id: development_deployment_id
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          deployments_count: 0
          instance_type_name: instance_type_name
          id: id
          production_deployment_id: production_deployment_id
        - development_deployment_id: development_deployment_id
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          deployments_count: 0
          instance_type_name: instance_type_name
          id: id
          production_deployment_id: production_deployment_id
      properties:
        models:
          items:
            $ref: '#/components/schemas/ModelV1'
          title: Models
          type: array
      required:
      - models
      title: ModelsV1
      type: object
      x-konfig-is-used-in-successful-response: true
    AutoscalingSettingsV1:
      description: Autoscaling settings for a deployment.
      example:
        scale_down_delay: 5
        min_replica: 6
        max_replica: 1
        concurrency_target: 2
        autoscaling_window: 5
      properties:
        min_replica:
          description: Minimum number of replicas
          title: Min Replica
          type: integer
        max_replica:
          description: Maximum number of replicas
          title: Max Replica
          type: integer
        autoscaling_window:
          description: Timeframe of traffic considered for autoscaling decisions
          title: Autoscaling Window
          type: integer
        scale_down_delay:
          description: Waiting period before scaling down any active replica
          title: Scale Down Delay
          type: integer
        concurrency_target:
          description: Number of requests per replica before scaling up
          title: Concurrency Target
          type: integer
      required:
      - autoscaling_window
      - concurrency_target
      - max_replica
      - min_replica
      - scale_down_delay
      title: AutoscalingSettingsV1
      type: object
    DeploymentStatusV1:
      description: The status of a deployment.
      enum:
      - BUILDING
      - DEPLOYING
      - DEPLOY_FAILED
      - LOADING_MODEL
      - ACTIVE
      - UNHEALTHY
      - BUILD_FAILED
      - BUILD_STOPPED
      - DEACTIVATING
      - INACTIVE
      - FAILED
      - UPDATING
      - SCALED_TO_ZERO
      - WAKING_UP
      title: DeploymentStatusV1
      type: string
    DeploymentV1:
      description: A deployment of a model.
      example:
        autoscaling_settings:
          scale_down_delay: 5
          min_replica: 6
          max_replica: 1
          concurrency_target: 2
          autoscaling_window: 5
        name: name
        is_production: true
        created_at: 2000-01-23T04:56:07.000+00:00
        active_replica_count: 0
        id: id
        model_id: model_id
        is_development: true
        status: null
      properties:
        id:
          description: Unique identifier of the deployment
          title: Id
          type: string
        created_at:
          description: Time the deployment was created in ISO 8601 format
          format: date-time
          title: Created At
          type: string
        name:
          description: Name of the deployment
          title: Name
          type: string
        model_id:
          description: Unique identifier of the model
          title: Model Id
          type: string
        is_production:
          description: Whether the deployment is the production deployment of the
            model
          title: Is Production
          type: boolean
        is_development:
          description: Whether the deployment is the development deployment of the
            model
          title: Is Development
          type: boolean
        status:
          $ref: '#/components/schemas/DeploymentStatusV1'
        active_replica_count:
          description: Number of active replicas
          title: Active Replica Count
          type: integer
        autoscaling_settings:
          $ref: '#/components/schemas/AutoscalingSettingsV1'
      required:
      - active_replica_count
      - autoscaling_settings
      - created_at
      - id
      - is_development
      - is_production
      - model_id
      - name
      - status
      title: DeploymentV1
      type: object
      x-konfig-properties:
        status:
          description: Status of the deployment
        autoscaling_settings:
          description: Autoscaling settings for the deployment
      x-konfig-is-used-in-successful-response: true
    DeploymentsV1:
      description: A list of deployments of a model.
      example:
        deployments:
        - autoscaling_settings:
            scale_down_delay: 5
            min_replica: 6
            max_replica: 1
            concurrency_target: 2
            autoscaling_window: 5
          name: name
          is_production: true
          created_at: 2000-01-23T04:56:07.000+00:00
          active_replica_count: 0
          id: id
          model_id: model_id
          is_development: true
          status: null
        - autoscaling_settings:
            scale_down_delay: 5
            min_replica: 6
            max_replica: 1
            concurrency_target: 2
            autoscaling_window: 5
          name: name
          is_production: true
          created_at: 2000-01-23T04:56:07.000+00:00
          active_replica_count: 0
          id: id
          model_id: model_id
          is_development: true
          status: null
      properties:
        deployments:
          description: A list of deployments of a model
          items:
            $ref: '#/components/schemas/DeploymentV1'
          title: Deployments
          type: array
      required:
      - deployments
      title: DeploymentsV1
      type: object
      x-konfig-is-used-in-successful-response: true
    UpdateAutoscalingSettingsV1:
      description: "A request to update autoscaling settings for a deployment. All\
        \ fields are optional, and we only update ones passed in."
      example:
        scale_down_delay: 5
        min_replica: 0
        max_replica: 6
        concurrency_target: 5
        autoscaling_window: 1
      properties:
        min_replica:
          description: Minimum number of replicas
          title: Min Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-min_replica
          example: null
        max_replica:
          description: Maximum number of replicas
          title: Max Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-max_replica
          example: null
        autoscaling_window:
          description: Timeframe of traffic considered for autoscaling decisions
          title: Autoscaling Window
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-autoscaling_window
          example: null
        scale_down_delay:
          description: Waiting period before scaling down any active replica
          title: Scale Down Delay
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-scale_down_delay
          example: null
        concurrency_target:
          description: Number of requests per replica before scaling up
          title: Concurrency Target
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-concurrency_target
          example: null
      title: UpdateAutoscalingSettingsV1
      type: object
    UpdateAutoscalingSettingsStatusV1:
      description: The status of a request to update autoscaling settings.
      enum:
      - ACCEPTED
      - QUEUED
      - UNCHANGED
      title: UpdateAutoscalingSettingsStatusV1
      type: string
    UpdateAutoscalingSettingsResponseV1:
      description: The response to a request to update autoscaling settings.
      example:
        message: message
        status: null
      properties:
        status:
          $ref: '#/components/schemas/UpdateAutoscalingSettingsStatusV1'
        message:
          description: A message describing the status of the request to update autoscaling
            settings
          title: Message
          type: string
      required:
      - message
      - status
      title: UpdateAutoscalingSettingsResponseV1
      type: object
      x-konfig-properties:
        status:
          description: Status of the request to update autoscaling settings
      x-konfig-is-used-in-successful-response: true
    PromoteRequestV1:
      description: A request to promote a deployment to production.
      example:
        scale_down_previous_production: true
      properties:
        scale_down_previous_production:
          default: true
          description: Whether to scale down the previous production deployment after
            promoting
          example: true
          title: Scale Down Previous Production
          type: boolean
          x-konfig-original-example: true
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-PromoteRequestV1-properties-scale_down_previous_production
      title: PromoteRequestV1
      type: object
    konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-min_replica:
      nullable: true
      type: string
      x-konfig-null-placeholder: true
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-max_replica:
      nullable: true
      type: string
      x-konfig-null-placeholder: true
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-autoscaling_window:
      nullable: true
      type: string
      x-konfig-null-placeholder: true
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-scale_down_delay:
      nullable: true
      type: string
      x-konfig-null-placeholder: true
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-concurrency_target:
      nullable: true
      type: string
      x-konfig-null-placeholder: true
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-PromoteRequestV1-properties-scale_down_previous_production:
      example: true
      type: boolean
      x-do-not-generate: true
    konfig-generated-schema-single-parameter-schema-get--v1-secrets:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-post--v1-secrets:
      properties:
        name:
          description: Name of the new or existing secret
          title: Name
          type: string
        value:
          description: Value of the secret
          title: Value
          type: string
      required:
      - name
      - value
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v1-models:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v1-models-model_id:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments-development:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments-production:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v1-models-model_id-deployments-deployment_id:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-patch--v1-models-model_id-deployments-development-autoscaling_settings:
      properties:
        min_replica:
          description: Minimum number of replicas
          title: Min Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-min_replica
          example: null
        max_replica:
          description: Maximum number of replicas
          title: Max Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-max_replica
          example: null
        autoscaling_window:
          description: Timeframe of traffic considered for autoscaling decisions
          title: Autoscaling Window
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-autoscaling_window
          example: null
        scale_down_delay:
          description: Waiting period before scaling down any active replica
          title: Scale Down Delay
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-scale_down_delay
          example: null
        concurrency_target:
          description: Number of requests per replica before scaling up
          title: Concurrency Target
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-concurrency_target
          example: null
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-patch--v1-models-model_id-deployments-production-autoscaling_settings:
      properties:
        min_replica:
          description: Minimum number of replicas
          title: Min Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-min_replica
          example: null
        max_replica:
          description: Maximum number of replicas
          title: Max Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-max_replica
          example: null
        autoscaling_window:
          description: Timeframe of traffic considered for autoscaling decisions
          title: Autoscaling Window
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-autoscaling_window
          example: null
        scale_down_delay:
          description: Waiting period before scaling down any active replica
          title: Scale Down Delay
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-scale_down_delay
          example: null
        concurrency_target:
          description: Number of requests per replica before scaling up
          title: Concurrency Target
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-concurrency_target
          example: null
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-patch--v1-models-model_id-deployments-deployment_id-autoscaling_settings:
      properties:
        min_replica:
          description: Minimum number of replicas
          title: Min Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-min_replica
          example: null
        max_replica:
          description: Maximum number of replicas
          title: Max Replica
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-max_replica
          example: null
        autoscaling_window:
          description: Timeframe of traffic considered for autoscaling decisions
          title: Autoscaling Window
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-autoscaling_window
          example: null
        scale_down_delay:
          description: Waiting period before scaling down any active replica
          title: Scale Down Delay
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-scale_down_delay
          example: null
        concurrency_target:
          description: Number of requests per replica before scaling up
          title: Concurrency Target
          type: integer
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-UpdateAutoscalingSettingsV1-properties-concurrency_target
          example: null
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-post--v1-models-model_id-deployments-development-promote:
      properties:
        scale_down_previous_production:
          default: true
          description: Whether to scale down the previous production deployment after
            promoting
          example: true
          title: Scale Down Previous Production
          type: boolean
          x-konfig-original-example: true
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-PromoteRequestV1-properties-scale_down_previous_production
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-post--v1-models-model_id-deployments-deployment_id-promote:
      properties:
        scale_down_previous_production:
          default: true
          description: Whether to scale down the previous production deployment after
            promoting
          example: true
          title: Scale Down Previous Production
          type: boolean
          x-konfig-original-example: true
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-PromoteRequestV1-properties-scale_down_previous_production
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
  securitySchemes:
    ApiKeyAuth:
      description: "You must use the specify the scheme 'Api-Key' in the Authorization\
        \ header. For example, `Authorization: Api-Key <Your_Api_Key>`"
      in: header
      name: Authorization
      type: apiKey
      x-konfig-globally-required-security: true

